import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "pt" | "es" | "zh" | "fr" | "ht" | "vi" | "ar" | "ru" | "hi" | "it";

interface LanguageContextType {
    language: Language;
    direction: "ltr" | "rtl";
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        // Header
        "nav.find_pro": "Find a Pro",
        "nav.about": "About",
        "nav.portfolio": "Portfolio",
        "nav.experiences": "Experiences",
        "nav.login": "Login",
        "nav.join_pro": "Join As a Pro",
        "nav.customer_portal": "Customer Portal",
        "nav.management_portal": "Management Portal",
        "nav.pros_login": "Pros Login",
        "nav.admin_panel": "Admin Panel",
        "nav.my_projects": "My Projects",
        "nav.sign_in": "Sign In",
        "nav.sign_out": "Sign Out",
        "nav.admin_login": "Admin Login",
        "nav.back_to_site": "Back to Site",
        "nav.language": "Language",

        // Hero
        "hero.title": "Your Home. Happier.",
        "hero.subtitle": "Finding the right contractor is fast, easy and free!",
        "hero.search_placeholder": "What type of pro are you looking for?",
        "hero.start": "Start",

        // Navigation
        "nav.back": "Back",
        "nav.service_not_found": "Service Not Found",
        "nav.browse_services": "Browse All Services",

        // Quote Form
        "quote.zip_code": "Zip Code",
        "quote.city": "City",
        "quote.state": "State",
        "quote.where_project": "Where is your project located?",
        "quote.service_type": "What type of service do you need?",
        "quote.details_title": "Add details for more exact quotes",
        "quote.details_desc": "Describe your project so pros can give you a better estimate.",
        "quote.contact_title": "Contact Information",
        "quote.contact_desc": "Get your free quotes now — no obligation.",
        "quote.full_name": "Full Name",
        "quote.address": "Street Address",
        "quote.email": "Email",
        "quote.phone": "Phone",
        "quote.continue": "Continue",
        "quote.submit": "Get my free quote",

        // Admin
        "admin.save": "Save",
        "admin.saving": "Saving...",
        "admin.save_estimate": "Save Estimate",
        "admin.settings": "Settings",
        "admin.company": "Company",
        "admin.dashboard": "Dashboard",
        "admin.estimates": "Estimates",
        "admin.reviews": "Reviews",
        "admin.analytics": "Analytics",
        "admin.locations": "Locations",
        "admin.status.draft": "Draft",
        "admin.status.sent": "Sent",
        "admin.status.viewed": "Viewed",
        "admin.status.approved": "Approved",
        "admin.status.rejected": "Rejected",
        "admin.status.expired": "Expired",
        "admin.status.paid": "Paid",
        "admin.status.partially_paid": "Partially Paid",
        "admin.payment.register": "Register Payment",
        "admin.payment.amount": "Amount",
        "admin.payment.method": "Method",
        "admin.payment.date": "Date",
        "admin.payment.summary": "Payment Summary",
        "admin.payment.paid": "Amount Paid",
        "admin.payment.balance": "Balance Due",
        "admin.project.type": "Project Type",
        "admin.project.kitchen": "Kitchen Remodel",
        "admin.project.bathroom": "Bathroom Remodel",
        "admin.project.deck": "Deck Build",
        "admin.project.framing": "Framing",
        "admin.project.trim": "Trim Work",
        "admin.project.custom": "Custom Carpentry",
        "admin.project.roofing": "Roofing Repair",
        "admin.project.siding": "Siding",
        "admin.project.general": "General Repair",
        "admin.revenue": "Total Revenue",
        "admin.outstanding": "Outstanding Balance",
        "admin.pending": "Pending Estimates",

        // Services
        "service.carpentry": "Carpentry",
        "service.plumbing": "Plumbing",
        "service.remodeling": "Remodeling",
        "service.roofing": "Roofing",
        "service.cleaning": "Cleaning",
        "service.air-conditioning": "Air Conditioning",
        "service.drywall": "Drywall",
        "service.electrician": "Electrician",
        "service.fencing": "Fencing",
        "service.flooring": "Flooring",
        "service.painting": "Painting",
        "service.tile": "Tile",
        "service.handyman": "Handyman",
    },
    pt: {
        "nav.find_pro": "Encontrar Profissional",
        "nav.about": "Sobre",
        "nav.portfolio": "Portfólio",
        "nav.experiences": "Experiências",
        "nav.login": "Entrar",
        "nav.join_pro": "Seja um Profissional",
        "nav.customer_portal": "Portal do Cliente",
        "nav.management_portal": "Portal de Gestão",
        "nav.pros_login": "Login de Pros",
        "nav.admin_panel": "Painel Admin",
        "nav.my_projects": "Meus Projetos",
        "nav.sign_in": "Entrar",
        "nav.sign_out": "Sair",
        "nav.admin_login": "Login Admin",
        "nav.back_to_site": "Voltar ao Site",
        "nav.language": "Idioma",

        // Hero
        "hero.title": "Sua Casa. Mais Feliz.",
        "hero.subtitle": "Encontrar o empreiteiro certo é rápido, fácil e grátis!",
        "hero.search_placeholder": "Que tipo de profissional você procura?",
        "hero.start": "Começar",

        // Navigation
        "nav.back": "Voltar",
        "nav.service_not_found": "Serviço Não Encontrado",
        "nav.browse_services": "Ver Todos os Serviços",


        "quote.zip_code": "CEP",
        "quote.city": "Cidade",
        "quote.state": "Estado",
        "quote.where_project": "Onde seu projeto está localizado?",
        "quote.service_type": "Que tipo de serviço você precisa?",
        "quote.details_title": "Adicione detalhes para orçamentos exatos",
        "quote.details_desc": "Descreva seu projeto para que os profissionais possam dar um orçamento melhor.",
        "quote.contact_title": "Informações de Contato",
        "quote.contact_desc": "Receba seus orçamentos grátis agora — sem compromisso.",
        "quote.full_name": "Nome Completo",
        "quote.address": "Endereço (Rua, Nº, Apto)",
        "quote.email": "E-mail",
        "quote.phone": "Telefone",
        "quote.continue": "Continuar",
        "quote.submit": "Solicitar orçamento grátis",
        "admin.save": "Salvar",
        "admin.saving": "Salvando...",
        "admin.save_estimate": "Salvar Orçamento",
        "admin.settings": "Configurações",
        "admin.company": "Empresa",
        "admin.dashboard": "Painel",
        "admin.estimates": "Orçamentos",
        "admin.reviews": "Avaliações",
        "admin.analytics": "Análise",
        "admin.locations": "Locais",
        "admin.status.draft": "Rascunho",
        "admin.status.sent": "Enviado",
        "admin.status.viewed": "Visualizado",
        "admin.status.approved": "Aprovado",
        "admin.status.rejected": "Rejeitado",
        "admin.status.expired": "Expirado",
        "admin.status.paid": "Pago",
        "admin.status.partially_paid": "Parcialmente Pago",
        "admin.payment.register": "Registrar Pagamento",
        "admin.payment.amount": "Valor",
        "admin.payment.method": "Método",
        "admin.payment.date": "Data",
        "admin.payment.summary": "Resumo de Pagamento",
        "admin.payment.paid": "Valor Pago",
        "admin.payment.balance": "Saldo Devedor",
        "admin.project.type": "Tipo de Projeto",
        "admin.project.kitchen": "Reforma de Cozinha",
        "admin.project.bathroom": "Reforma de Banheiro",
        "admin.project.deck": "Construção de Deck",
        "admin.project.framing": "Framing (Estrutura)",
        "admin.project.trim": "Trim Work (Acabamento)",
        "admin.project.custom": "Carpintaria Sob Medida",
        "admin.project.roofing": "Conserto de Telhado",
        "admin.project.siding": "Siding (Revestimento)",
        "admin.project.general": "Conserto Geral",
        "admin.revenue": "Faturamento Total",
        "admin.outstanding": "Saldo Pendente",
        "admin.pending": "Orçamentos Pendentes",
        "admin.approved_count": "Orçamentos Aprovados",
        "admin.rejected_count": "Orçamentos Rejeitados",

        // Services
        "service.carpentry": "Carpintaria",
        "service.plumbing": "Encanamento",
        "service.remodeling": "Reforma",
        "service.roofing": "Telhado",
        "service.cleaning": "Limpeza",
        "service.air-conditioning": "Ar Condicionado",
        "service.drywall": "Drywall",
        "service.electrician": "Eletricista",
        "service.fencing": "Cerca",
        "service.flooring": "Pisos",
        "service.painting": "Pintura",
        "service.tile": "Azulejo",
        "service.handyman": "Handyman",
    },
    es: {
        "nav.find_pro": "Encontrar un Pro",
        "nav.about": "Sobre nosotros",
        "nav.portfolio": "Portafolio",
        "nav.experiences": "Experiencias",
        "nav.login": "Entrar",
        "nav.join_pro": "Únete como Pro",
        "nav.customer_portal": "Portal del Cliente",
        "nav.management_portal": "Portal de Gestión",
        "nav.pros_login": "Login de Pros",
        "nav.admin_panel": "Panel Admin",
        "nav.my_projects": "Mis Proyectos",
        "nav.sign_in": "Entrar",
        "nav.sign_out": "Salir",
        "nav.admin_login": "Login Admin",
        "nav.back_to_site": "Volver al Sitio",
        "nav.language": "Idioma",

        // Hero
        "hero.title": "Tu Hogar. Más Feliz.",
        "hero.subtitle": "¡Encontrar al contratista adecuado es rápido, fácil y gratis!",
        "hero.search_placeholder": "¿Qué tipo de profesional buscas?",
        "hero.start": "Empezar",

        "quote.zip_code": "Código Postal",
        "quote.city": "Ciudad",
        "quote.state": "Estado",
        "quote.where_project": "¿Dónde se encontra su proyecto?",
        "quote.service_type": "¿Qué tipo de servicio necesita?",
        "quote.details_title": "Añada detalles para presupuestos exactos",
        "quote.details_desc": "Describa su proyecto para que los profesionales puedan dar un mejor presupuesto.",
        "quote.contact_title": "Información de Contacto",
        "quote.contact_desc": "Obtenga sus presupuestos gratis ahora — sin compromiso.",
        "quote.full_name": "Nombre Completo",
        "quote.address": "Dirección (Calle, Nº, Apto)",
        "quote.email": "Correo electrónico",
        "quote.phone": "Teléfono",
        "quote.continue": "Continuar",
        "quote.submit": "Obtener mi presupuesto gratis",
        "admin.save": "Guardar",
        "admin.saving": "Guardando...",
        "admin.save_estimate": "Guardar Presupuesto",
        "admin.settings": "Configuraciones",
        "admin.company": "Empresa",
        "admin.dashboard": "Panel",

        // Services
        "service.carpentry": "Carpintería",
        "service.plumbing": "Fontanería",
        "service.remodeling": "Remodelación",
        "service.roofing": "Techado",
        "service.cleaning": "Limpieza",
        "service.air-conditioning": "Aire Acondicionado",
        "service.drywall": "Drywall",
        "service.electrician": "Electricista",
        "service.fencing": "Cercas",
        "service.flooring": "Pisos",
        "service.painting": "Pintura",
        "service.tile": "Azulejo",
        "service.handyman": "Handyman",
    },
    zh: {
        "nav.find_pro": "寻找专家",
        "nav.about": "关于我们",
        "nav.portfolio": "作品集",
        "nav.experiences": "经验分享",
        "nav.login": "登录",
        "nav.join_pro": "加入我们",
        "nav.customer_portal": "客户门户",
        "nav.management_portal": "管理门户",
        "nav.pros_login": "专家登录",
        "nav.admin_panel": "管理面板",
        "nav.my_projects": "我的项目",
        "nav.sign_in": "登录",
        "nav.sign_out": "退出",
        "nav.admin_login": "管理员登录",
        "nav.back_to_site": "返回网站",
        "nav.language": "语言",

        // Hero
        "hero.title": "您的家，更快乐。",
        "hero.subtitle": "寻找合适的承包商是快速、简单且免费的！",
        "hero.search_placeholder": "您在寻找什么类型的专家？",
        "hero.start": "开始",

        "quote.zip_code": "邮政编码",
        "quote.city": "城市",
        "quote.state": "州",
        "quote.where_project": "您的项目位于何处？",
        "quote.service_type": "您需要什么类型的服务？",
        "quote.details_title": "添加详细信息以获取准确报价",
        "quote.details_desc": "描述您的项目，以便专家提供更好的估算。",
        "quote.contact_title": "联系信息",
        "quote.contact_desc": "立即获取免费报价 — 无需承担任何义务。",
        "quote.full_name": "全名",
        "quote.address": "详细地址（街道、号码、公寓）",
        "quote.email": "电子邮件",
        "quote.phone": "电话",
        "quote.continue": "继续",
        "quote.submit": "获取我的免费报价",
        "admin.save": "保存",
        "admin.saving": "保存中...",
        "admin.save_estimate": "保存估算",
        "admin.settings": "设置",
        "admin.company": "企业",
        "admin.dashboard": "仪表板",

        // Services
        "service.carpentry": "木工",
        "service.plumbing": "管道",
        "service.remodeling": "翻新",
        "service.roofing": "屋顶",
        "service.cleaning": "清洁",
        "service.air-conditioning": "空调",
        "service.drywall": "干墙",
        "service.electrician": "电工",
        "service.fencing": "栅栏",
        "service.flooring": "地板",
        "service.painting": "油漆",
        "service.tile": "瓷砖",
        "service.handyman": "杂工",
    },
    fr: {
        "nav.find_pro": "Trouver un pro",
        "nav.about": "À propos",
        "nav.portfolio": "Portfolio",
        "nav.experiences": "Expériences",
        "nav.login": "Connexion",
        "nav.join_pro": "Devenir Pro",
        "nav.customer_portal": "Portail Client",
        "nav.management_portal": "Portail de Gestion",
        "nav.pros_login": "Connexion Pros",
        "nav.admin_panel": "Panneau Admin",
        "nav.my_projects": "Mes Projets",
        "nav.sign_in": "Se connecter",
        "nav.sign_out": "Se déconnecter",
        "nav.admin_login": "Connexion Admin",
        "nav.back_to_site": "Retour au Site",
        "nav.language": "Langue",

        // Hero
        "hero.title": "Votre Maison. Plus Heureuse.",
        "hero.subtitle": "Trouver le bon entrepreneur est rapide, facile et gratuit !",
        "hero.search_placeholder": "Quel type de pro recherchez-vous ?",
        "hero.start": "Démarrer",

        "quote.zip_code": "Code Postal",
        "quote.city": "Ville",
        "quote.state": "État",
        "quote.where_project": "Où se situe votre projet ?",
        "quote.service_type": "De quel type de service avez-vous besoin ?",
        "quote.details_title": "Détails pour des devis plus précis",
        "quote.details_desc": "Décrivez votre projet pour de meilleurs devis.",
        "quote.contact_title": "Informations de Contact",
        "quote.contact_desc": "Devis gratuits maintenant — sans engagement.",
        "quote.full_name": "Nom Complet",
        "quote.address": "Adresse (Rue, Nº, Appt)",
        "quote.email": "E-mail",
        "quote.phone": "Téléphone",
        "quote.continue": "Continuer",
        "quote.submit": "Obtenir mon devis gratuit",
        "admin.save": "Enregistrer",
        "admin.saving": "Enregistrement...",
        "admin.save_estimate": "Enregistrer le devis",
        "admin.settings": "Réglages",
        "admin.company": "Entreprise",
        "admin.dashboard": "Tableau de Bord",

        // Services
        "service.carpentry": "Charpenterie",
        "service.plumbing": "Plomberie",
        "service.remodeling": "Remodelage",
        "service.roofing": "Toiture",
        "service.cleaning": "Nettoyage",
        "service.air-conditioning": "Climatisation",
        "service.drywall": "Cloison sèche",
        "service.electrician": "Électricien",
        "service.fencing": "Clôture",
        "service.flooring": "Revêtement de sol",
        "service.painting": "Peinture",
        "service.tile": "Carrelage",
        "service.handyman": "Bricoleur",
    },
    ht: {
        "nav.find_pro": "Jwenn yon Pro",
        "nav.about": "Konsènan",
        "nav.portfolio": "Pòtfolyo",
        "nav.experiences": "Esperyans",
        "nav.login": "Konekte",
        "nav.join_pro": "Rantre kòm Pro",
        "nav.customer_portal": "Pòtal Kliyan",
        "nav.management_portal": "Pòtal Jesyon",
        "nav.pros_login": "Login Pros",
        "nav.admin_panel": "Panèl Admin",
        "nav.my_projects": "Pwojè mwen yo",
        "nav.sign_in": "Loge",
        "nav.sign_out": "Dekonekte",
        "nav.admin_login": "Login Admin",
        "nav.back_to_site": "Retounen sou Sit la",
        "nav.language": "Langaj",

        // Hero
        "hero.title": "Kay Ou. Plis Kontan.",
        "hero.subtitle": "Jwenn bon kontraktè a rapid, fasil epi gratis!",
        "hero.search_placeholder": "Ki kalite pro w ap chèche?",
        "hero.start": "Kòmanse",

        "quote.zip_code": "Kòd Postal",
        "quote.city": "Vil",
        "quote.state": "Eta",
        "quote.where_project": "Ki kote pwojè w la ye?",
        "quote.service_type": "Ki kalite sèvis ou bezwen?",
        "quote.details_title": "Ajoute detay pou sitasyon egzak",
        "quote.details_desc": "Dekri pwojè w la pou pro yo ka ba w yon pi bon estimasyon.",
        "quote.contact_title": "Enfòmasyon Konsènan Kontak",
        "quote.contact_desc": "Jwenn sitasyon gratis ou konnye a — san obligasyon.",
        "quote.full_name": "Non Konplè",
        "quote.address": "Adrès (Ri, Nimewo, Apatman)",
        "quote.email": "Imèl",
        "quote.phone": "Telefòn",
        "quote.continue": "Kontinye",
        "quote.submit": "Jwenn sitasyon gratis mwen",
        "admin.save": "Sove",
        "admin.saving": "Ap sove...",
        "admin.save_estimate": "Sove Estimasyon",
        "admin.settings": "Anviwònman",
        "admin.company": "Konpayi",
        "admin.dashboard": "Tablo bò",

        // Services
        "service.carpentry": "Mennen",
        "service.plumbing": "Plonbri",
        "service.remodeling": "Remodelaj",
        "service.roofing": "Twati",
        "service.cleaning": "Netwayaj",
        "service.air-conditioning": "È kondisyone",
        "service.drywall": "Draywòl",
        "service.electrician": "Elektrisyen",
        "service.fencing": "Kloti",
        "service.flooring": "Planche",
        "service.painting": "Penti",
        "service.tile": "Til",
        "service.handyman": "Handyman",
    },
    vi: {
        "nav.find_pro": "Tìm Chuyên gia",
        "nav.about": "Giới thiệu",
        "nav.portfolio": "Hồ sơ",
        "nav.experiences": "Kinh nghiệm",
        "nav.login": "Đăng nhập",
        "nav.join_pro": "Gia nhập Chuyên gia",
        "nav.customer_portal": "Cổng Khách hàng",
        "nav.management_portal": "Cổng Quản lý",
        "nav.pros_login": "Đăng nhập Pro",
        "nav.admin_panel": "Bảng Admin",
        "nav.my_projects": "Dự án của tôi",
        "nav.sign_in": "Đăng nhập",
        "nav.sign_out": "Đăng xuất",
        "nav.admin_login": "Đăng nhập Admin",
        "nav.back_to_site": "Quay lại Trang web",
        "nav.language": "Ngôn ngữ",

        // Hero
        "hero.title": "Ngôi Nhà Bạn. Hạnh Phúc Hơn.",
        "hero.subtitle": "Tìm kiếm nhà thầu phù hợp thật nhanh chóng, dễ dàng và miễn phí!",
        "hero.search_placeholder": "Bạn đang tìm kiếm loại chuyên gia nào?",
        "hero.start": "Bắt đầu",

        "quote.zip_code": "Mã bưu chính",
        "quote.city": "Thành phố",
        "quote.state": "Bang",
        "quote.where_project": "Dự án của bạn ở đâu?",
        "quote.service_type": "Bạn cần loại dịch vụ nào?",
        "quote.details_title": "Thêm chi tiết để báo giá chính xác",
        "quote.details_desc": "Mô tả dự án để chuyên gia báo giá tốt hơn.",
        "quote.contact_title": "Thông tin Liên hệ",
        "quote.contact_desc": "Nhận báo giá miễn phí ngay — không bắt buộc.",
        "quote.full_name": "Họ và Tên",
        "quote.address": "Địa chỉ (Đường, Số nhà, Căn hộ)",
        "quote.email": "Email",
        "quote.phone": "Điện thoại",
        "quote.continue": "Tiếp tục",
        "quote.submit": "Nhận báo giá miễn phí",
        "admin.save": "Lưu",
        "admin.saving": "Đang lưu...",
        "admin.save_estimate": "Lưu báo giá",
        "admin.settings": "Cài đặt",
        "admin.company": "Công ty",
        "admin.dashboard": "Bảng điều khiển",

        // Services
        "service.carpentry": "Thợ mộc",
        "service.plumbing": "Hệ thống ống nước",
        "service.remodeling": "Tân trang",
        "service.roofing": "Lợp mái",
        "service.cleaning": "Dọn dẹp",
        "service.air-conditioning": "Máy lạnh",
        "service.drywall": "Tường thạch cao",
        "service.electrician": "Thợ điện",
        "service.fencing": "Hàng rào",
        "service.flooring": "Lát sàn",
        "service.painting": "Sơn",
        "service.tile": "Gạch",
        "service.handyman": "Thợ sửa vặt",
    },
    ar: {
        "nav.find_pro": "ابحث عن محترف",
        "nav.about": "حول",
        "nav.portfolio": "حقيبة الأعمال",
        "nav.experiences": "الخبرات",
        "nav.login": "تسجيل الدخول",
        "nav.join_pro": "انضم كمحترف",
        "nav.customer_portal": "بوابة العملاء",
        "nav.management_portal": "بوابة الإدارة",
        "nav.pros_login": "دخول المحترفين",
        "nav.admin_panel": "لوحة المدير",
        "nav.my_projects": "مشاريعي",
        "nav.sign_in": "دخول",
        "nav.sign_out": "خروج",
        "nav.admin_login": "دخول المدير",
        "nav.back_to_site": "العودة للموقع",
        "nav.language": "اللغة",

        // Hero
        "hero.title": "منزلك. أكثر سعادة.",
        "hero.subtitle": "العثور على المقاول المناسب سريع وسهل ومجاني!",
        "hero.search_placeholder": "ما هو نوع المحترف الذي تبحث عنه؟",
        "hero.start": "ابدأ",

        "quote.zip_code": "الرمز البريدي",
        "quote.city": "المدينة",
        "quote.state": "الولاية",
        "quote.where_project": "أين يقع مشروعك؟",
        "quote.service_type": "ما نوع الخدمة التي تحتاجها؟",
        "quote.details_title": "أضف تفاصيل للحصول على عروض أسعار دقيقة",
        "quote.details_desc": "صف مشروعك حتى يتمكن المحترفون من تقديم تقدير أفضل.",
        "quote.contact_title": "معلومات الاتصال",
        "quote.contact_desc": "احصل على عروض أسعار مجانية الآن — بدون التزام.",
        "quote.full_name": "الاسم الكامل",
        "quote.address": "العنوان (الشارع، الرقم، الشقة)",
        "quote.email": "البريد الإلكتروني",
        "quote.phone": "الهاتف",
        "quote.continue": "استمرار",
        "quote.submit": "احصل على عرض سعر مجاني",
        "admin.save": "حفظ",
        "admin.saving": "جاري الحفظ...",
        "admin.save_estimate": "حفظ التقدير",
        "admin.settings": "الإعدادات",
        "admin.company": "الشركة",
        "admin.dashboard": "لوحة القيادة",

        // Services
        "service.carpentry": "نجارة",
        "service.plumbing": "سباكة",
        "service.remodeling": "ترميم",
        "service.roofing": "تسقيف",
        "service.cleaning": "تنظيف",
        "service.air-conditioning": "تكييف",
        "service.drywall": "جبس",
        "service.electrician": "كهربائي",
        "service.fencing": "سياج",
        "service.flooring": "أرضيات",
        "service.painting": "صباغة",
        "service.tile": "بلاط",
        "service.handyman": "عامل صيانة",
    },
    ru: {
        "nav.find_pro": "Найти профи",
        "nav.about": "О нас",
        "nav.portfolio": "Портфолио",
        "nav.experiences": "Опыт",
        "nav.login": "Логин",
        "nav.join_pro": "Присоединиться",
        "nav.customer_portal": "Портал клиента",
        "nav.management_portal": "Портал управления",
        "nav.pros_login": "Вход для профи",
        "nav.admin_panel": "Панель админа",
        "nav.my_projects": "Мои проекты",
        "nav.sign_in": "Войти",
        "nav.sign_out": "Выйти",
        "nav.admin_login": "Вход для админа",
        "nav.back_to_site": "Вернуться на сайт",
        "nav.language": "Язык",

        // Hero
        "hero.title": "Ваш дом. Счастливее.",
        "hero.subtitle": "Найти подрядчика — это быстро, просто и бесплатно!",
        "hero.search_placeholder": "Какого мастера вы ищете?",
        "hero.start": "Начать",

        "quote.zip_code": "Почтовый индекс",
        "quote.city": "Город",
        "quote.state": "Штат",
        "quote.where_project": "Где находится ваш проект?",
        "quote.service_type": "Какая услуга вам нужна?",
        "quote.details_title": "Добавьте детали для точного расчета",
        "quote.details_desc": "Опишите проект, чтобы профи могли дать точную оценку.",
        "quote.contact_title": "Контактная информация",
        "quote.contact_desc": "Получите бесплатный расчет сейчас — без обязательств.",
        "quote.full_name": "Полное имя",
        "quote.address": "Адрес (улица, номер, кв.)",
        "quote.email": "Email",
        "quote.phone": "Телефон",
        "quote.continue": "Продолжить",
        "quote.submit": "Получить расчет",
        "admin.save": "Сохранить",
        "admin.saving": "Сохранение...",
        "admin.save_estimate": "Сохранить смету",
        "admin.settings": "Настройки",
        "admin.company": "Компания",
        "admin.dashboard": "Панель",

        // Services
        "service.carpentry": "Плотник",
        "service.plumbing": "Сантехник",
        "service.remodeling": "Ремонт",
        "service.roofing": "Кровля",
        "service.cleaning": "Уборка",
        "service.air-conditioning": "Кондиционер",
        "service.drywall": "Гипсокартон",
        "service.electrician": "Электрик",
        "service.fencing": "Заборы",
        "service.flooring": "Полы",
        "service.painting": "Покраска",
        "service.tile": "Плитка",
        "service.handyman": "Мастер",
    },
    hi: {
        "nav.find_pro": "प्रोफेशनल खोजें",
        "nav.about": "हमारे बारे में",
        "nav.portfolio": "पोर्टफोलियो",
        "nav.experiences": "अनुभव",
        "nav.login": "लॉगिन",
        "nav.join_pro": "प्रोफेशनल के रूप में जुड़ें",
        "nav.customer_portal": "ग्राहक पोर्टल",
        "nav.management_portal": "प्रबंधन पोर्टल",
        "nav.pros_login": "प्रो लॉगिन",
        "nav.admin_panel": "व्यवस्थापक पैनल",
        "nav.my_projects": "मेरी परियोजनाएं",
        "nav.sign_in": "साइन इन",
        "nav.sign_out": "साइन आउट",
        "nav.admin_login": "एडमिन लॉगिन",
        "nav.back_to_site": "साइट पर वापस जाएं",
        "nav.language": "भाषा",

        // Hero
        "hero.title": "आपका घर। खुशहाल।",
        "hero.subtitle": "सही ठेकेदार ढूँढना तेज़, आसान और मुफ़्त है!",
        "hero.search_placeholder": "आप किस प्रकार के प्रो की तलाश कर रहे हैं?",
        "hero.start": "शुरू करें",

        "quote.zip_code": "पिन कोड",
        "quote.city": "शहर",
        "quote.state": "राज्य",
        "quote.where_project": "आपकी परियोजना कहाँ स्थित है?",
        "quote.service_type": "आपको किस प्रकार की सेवा की आवश्यकता है?",
        "quote.details_title": "सटीक उद्धरण के लिए विवरण जोड़ें",
        "quote.details_desc": "अपनी परियोजना का वर्णन करें ताकि पेशेवर बेहतर अनुमान लगा सकें।",
        "quote.contact_title": "संपर्क जानकारी",
        "quote.contact_desc": "अभी अपना निःशुल्क उद्धरण प्राप्त करें — कोई बाध्यता नहीं।",
        "quote.full_name": "पूरा नाम",
        "quote.address": "पता (सड़क, नंबर, अपार्टमेंट)",
        "quote.email": "ईमेल",
        "quote.phone": "फोन",
        "quote.continue": "जारी रखें",
        "quote.submit": "मुफ़्त उद्धरण प्राप्त करें",
        "admin.save": "सहेजें",
        "admin.saving": "सहेज रहा है...",
        "admin.save_estimate": "अनुमान सहेजें",
        "admin.settings": "सेटिंग्स",
        "admin.company": "कंपनी",
        "admin.dashboard": "डैशबोर्ड",

        // Services
        "service.carpentry": "बढ़ईगिरी",
        "service.plumbing": "नलसाजी",
        "service.remodeling": "पुनर्निर्माण",
        "service.roofing": "छत",
        "service.cleaning": "सफाई",
        "service.air-conditioning": "वातानुकूलन",
        "service.drywall": "ड्रायवॉल",
        "service.electrician": "इलेक्ट्रीशियन",
        "service.fencing": "फेंसिंग",
        "service.flooring": "फ्लोरिंग",
        "service.painting": "पेंटिंग",
        "service.tile": "टाइल",
        "service.handyman": "हैंडीमैन",
    },
    it: {
        "nav.find_pro": "Trova un pro",
        "nav.about": "Chi siamo",
        "nav.portfolio": "Portfolio",
        "nav.experiences": "Esperienze",
        "nav.login": "Accedi",
        "nav.join_pro": "Unisciti come Pro",
        "nav.customer_portal": "Portale Clienti",
        "nav.management_portal": "Portale di Gestione",
        "nav.pros_login": "Login Pro",
        "nav.admin_panel": "Pannello Admin",
        "nav.my_projects": "I miei progetti",
        "nav.sign_in": "Accedi",
        "nav.sign_out": "Esci",
        "nav.admin_login": "Login Admin",
        "nav.back_to_site": "Torna al sito",
        "nav.language": "Lingua",

        // Hero
        "hero.title": "La Tua Casa. Più Felice.",
        "hero.subtitle": "Trovare l'impresa giusta è veloce, facile e gratuito!",
        "hero.search_placeholder": "Che tipo di professionista cerchi?",
        "hero.start": "Inizia",

        "quote.zip_code": "Codice Postale",
        "quote.city": "Città",
        "quote.state": "Provincia",
        "quote.where_project": "Dove si trova il tuo progetto?",
        "quote.service_type": "Di che tipo di servizio hai bisogno?",
        "quote.details_title": "Dettagli per preventivi più precisi",
        "quote.details_desc": "Descrivi il tuo progetto affinché i pro possano darti una stima migliore.",
        "quote.contact_title": "Informazioni di Contatto",
        "quote.contact_desc": "Preventivi gratuiti ora — senza impegno.",
        "quote.full_name": "Nome Completo",
        "quote.address": "Indirizzo (Via, N., App.)",
        "quote.email": "E-mail",
        "quote.phone": "Telefono",
        "quote.continue": "Continua",
        "quote.submit": "Ottieni preventivo gratuito",
        "admin.save": "Salva",
        "admin.saving": "Salvataggio...",
        "admin.save_estimate": "Salva preventivo",
        "admin.settings": "Impostazioni",
        "admin.company": "Azienda",
        "admin.dashboard": "Dashboard",

        // Services
        "service.carpentry": "Carpenteria",
        "service.plumbing": "Idraulica",
        "service.remodeling": "Ristrutturazione",
        "service.roofing": "Tetti",
        "service.cleaning": "Pulizia",
        "service.air-conditioning": "Climatizzazione",
        "service.drywall": "Cartongesso",
        "service.electrician": "Elettricista",
        "service.fencing": "Recinzioni",
        "service.flooring": "Pavimenti",
        "service.painting": "Pittura",
        "service.tile": "Piastrelle",
        "service.handyman": "Tuttofare",
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const supportedLanguages: Language[] = ["en", "pt", "es", "zh", "fr", "ht", "vi", "ar", "ru", "hi", "it"];

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>("en");
    const direction = language === "ar" ? "rtl" : "ltr";

    useEffect(() => {
        document.documentElement.dir = direction;
        document.documentElement.lang = language;
    }, [language, direction]);

    useEffect(() => {
        const saved = localStorage.getItem("preferred_language") as Language;
        if (saved && supportedLanguages.includes(saved)) {
            setLanguageState(saved);
        } else {
            const browserLang = navigator.language.split("-")[0] as any;
            if (supportedLanguages.includes(browserLang)) {
                setLanguageState(browserLang);
            }
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("preferred_language", lang);
    };

    const t = (key: string) => {
        return translations[language][key] || translations["en"][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, direction, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
};
